M48
; DRILL file KiCad 10.0.1 date 2026-05-13T21:49:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-13T21:49:13+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X89.11Y-156.9
X94.89Y-156.9
T2
X110.75Y-146.95
X110.75Y-153.95
M30
